es:
  image: elasticsearch
  ports:
    - 9200:9200
    - 9300:9300
  volumes:
    - /esdata:/usr/share/elasticsearch/data 

logger:
  image: logger
  ports:
    - 24224:24224
  links:
    - es:elasticsearch

kibana:
  image: kibana
  ports:
    - 5601:5601
  links:
    - es:elasticsearch
